### ISSUE TITLE
how to add email alert address

### ISSUE THREAD

**Issue by aliartiza75** [AntoineAugusti/updown#7]
Hi @AntoineAugusti,

I am using you go package for updown monitor and its rocking. Just want to know is there a way to add email alert addresses either by using your package or updown's REST API. 

I am unable to find any resource in that regards, help would be appreciated. 

Thank you
Irtiza

**Comment by AntoineAugusti** [comment]
Thanks Adrien! Closing for now.

**Comment by aliartiza75** [comment]
@AntoineAugusti is there any chance that you will add this feature in near future, I am available for contribution.

**Comment by aliartiza75** [comment]
@jarthod ack.

**Comment by aliartiza75** [comment]
feature request for this feature has been created, link to [feature request](https://updown.uservoice.com/forums/177972-general/suggestions/37334926-api-for-setting-email-and-phone-alerts-for-a-check)
